In [17]:
import numpy as np
A = np.arange(0,100,3)
A

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [28]:
B = np.sin (A*A*np.pi/2)
B

array([ 0.00000000e+00,  1.00000000e+00, -2.20436424e-15,  1.00000000e+00,
       -8.81745695e-15,  1.00000000e+00, -4.11555602e-14,  1.00000000e+00,
       -3.52698278e-14,  1.00000000e+00, -7.64253880e-14,  1.00000000e+00,
       -1.64622241e-13,  1.00000000e+00, -1.86173549e-13,  1.00000000e+00,
       -1.41079311e-13,  1.00000000e+00, -4.84086880e-13,  1.00000000e+00,
       -3.05701552e-13,  1.00000000e+00, -6.06706795e-14,  1.00000000e+00,
       -6.58488964e-13,  1.00000000e+00, -1.18966170e-12,  1.00000000e+00,
       -7.44694194e-13,  1.00000000e+00, -1.14257584e-12,  1.00000000e+00,
       -5.64317245e-13,  1.00000000e+00])

In [32]:
C= B.max()
C

1.0

In [54]:
x = np.argmax(B) 
y = x.size
y

1

In [61]:
np.count_nonzero (B==C)    

17

In [1]:
import numpy as np
M=np.array([[1,0,0], [0,1,0], [0,0,1]])
B= np.triu(M)
C= np.tril(B)
(B==C).all()
def est_diagonale(M): 
    if (M==C).all() :
        return "True"
    else : "false"
est_diagonale(M)

    
    

'True'

In [20]:
import numpy as np
def est_traingulaire_sup(M):
    M = np.array([[1,1,1], [0,1,1], [1,0,1]])
    B=np.triu(M)
    if (M == B).all() : 
        print("True")
    else : print("false")
est_traingulaire_sup(M)

false


In [6]:
import numpy as np
a = np.ones((8,8))
for i in range(8):
    for j in range(8):
        a [i][j] = 1
a[0:-1, 1:-1] = 0
print (a)

b = np.ones((8,8))
b[0:-1, 1:-1] = 0
print(b)


c = np.ones((8,4))
d = np.ones((8,4))
e = np.concatenate ((c,d), axis=1)
e [0:-1, 1:-1] = 0
print (e)

[[1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [24]:
n = 10
for entier in range (0,n+1) :
    print(entier)

0
1
2
3
4
5
6
7
8
9
10


In [50]:
import time
n = 10
somme = 0
t0 = time.clock()
for entier in range (0,n+1) :
    somme = somme + entier
    print(somme)
print (time.clock())

0
1
3
6
10
15
21
28
36
45
55
6795.637550992


C:\Users\Dell\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  after removing the cwd from sys.path.
C:\Users\Dell\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  


In [51]:
n = 10 
tableau = np.arange (n+1)
t0 = time.clock()
somme = tableau.sum()
somme
print (time.clock())

6798.330328163


C:\Users\Dell\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\Dell\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  


In [99]:
absVal = 0
a = np.random.rand(50,50)
for ligne in range (0,50) :
    for col in range (0,49) :
        relatif = np.abs(a[ligne][col]-a[ligne][col+1])
        if  relatif > absVal:
            absVal = relatif
print (absVal)

0.9798198107530735


In [132]:
A = np.random.rand(50,50)
resultat =  0 
for ligne in range (0,50) :
    for col in range (0,50) :
        resultat = resultat + (A[ligne][col]<0.5)
print (resultat)


1219


In [135]:
A = np.random.rand(50,50)
for ligne in range (0,50) :
    for col in range (0,50) :
        A[ligne][col] = (1,0)[A[ligne][col]<0.5]
print (A)





[[1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 1. 0. 1.]
 [1. 1. 0. ... 0. 0. 0.]
 ...
 [1. 1. 0. ... 0. 1. 1.]
 [0. 1. 0. ... 0. 0. 1.]
 [0. 1. 1. ... 0. 1. 1.]]


C:\Users\Dell\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DeprecationWarning: In future, it will be an error for 'np.bool_' scalars to be interpreted as an index
  """


In [137]:
A = np.random.rand(50,50)
for ligne in range (0,50) :
    for col in range (0,50) :
        if A[ligne][col] <0.5:
            A[ligne][col] = 0
        else : 
            A[ligne][col] = 1
print (A)

[[1. 0. 0. ... 1. 1. 0.]
 [1. 0. 1. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 ...
 [1. 0. 0. ... 1. 1. 1.]
 [1. 0. 0. ... 1. 1. 0.]
 [1. 0. 1. ... 0. 0. 1.]]
